// Google Business Reviews - Real reviews from Google
export const googleReviews = [
  {
    name: "Sumaiya Rufida",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "I had a great experience learning with Lakshmi. Her instructions were always very clear and easy to understand. She was extremely patient with me and kept correcting my recurring mistakes again and again without ever losing her calm.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Sampatti Kohli",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "My experience with Lakshmi as my driving instructor was truly amazing. She played a huge role in building a strong foundation for my driving skills and helped me overcome my fears with so much patience and confidence. I would highly recommend her to anyone looking for a supportive and knowledgeable instructor.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Spandana Metuku",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "I had an amazing experience learning with Alluri Lakshmi. She is incredibly professional, patient, and highly experienced. Her clear instructions and confidence-building approach made a huge difference in my learning journey.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Blessing Lasubulu",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "I had an amazing experience with Lucky Driving School and my instructor Lakshmi. Lakshmi is an outstanding professional who is patient, highly skilled and dedicated to helping students succeed.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Rekha",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "We are very thankful to Lucky Driving School for the excellent training they gave my daughter. The instructor, Lakshmi, was very patient, supportive, and provided high-quality, dedicated training. She explained every nook and corner of driving thoroughly.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Namish Moduga",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Instructor Lakshmi was such an amazing teacher! Having lots of patience and attention while I was driving, I was able to learn quickly from her. She provided ample tips and tricks to driving that made it so much easier to drive and would highly recommend coming here to learn regardless of driving experience.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Glory",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Highly recommend Lucky driving school! Lakshmi is an amazing instructor - patient, encouraging, and makes learning to drive a breeze. Her instruction style is clear, firm, and super supportive, perfect for nervous learners like me.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Nidhi Kang",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "I had an amazing experience with my driving instructor. This was my first time ever driving, and I'm in my forties. I was honestly terrified of even thinking about driving—but with her guidance, I passed my Class 5 test without a single mistake.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Ghada Aborkhees",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Lakshmi was an outstanding driving instructor. This was the first time I worked with someone who truly understood driving anxiety and the challenges that come with it. After years of unsuccessful attempts, she helped turn repeated failure into success.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Hardi Suthar",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "I'm very happy with my experience with your Lucky driving school. Lakshmi explained everything clearly and focused on building confidence and safe driving skills. Thanks to your guidance, I passed my driving test on the first try.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Deepthi Randhi",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "I had a wonderful experience learning to drive at Lucky Driving School. My instructor, Lakshmi Alluri, was very patient, supportive, and professional. She explained everything clearly and helped me build confidence behind the wheel.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Minaz Modi",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "I can't thank Ms. Lakshmi enough for what she's done for me. After failing my road test earlier, I had almost completely lost my confidence and started doubting my driving abilities. Ms. Lakshmi changed that. From day one, she believed in me and helped me succeed.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Naresh Gajarao",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "I had a fantastic experience with Lucky Driving School. My instructor, Lakshmi Prasanna, was incredibly patient, knowledgeable, and supportive throughout the entire learning process. She explained everything clearly, corrected my mistakes with care.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Tristan",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "I'm very thankful for Lucky driving school. Lakshmi is a great teacher. She gave me lots of help and tips that were able to help me pass my road exam first try very easily. Furthermore, she has excellent hours and was always able to work around my schedule.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Daniel Brhane",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "I had an excellent experience learning with my lady instructor. She is patient, calm, and very professional. She explains everything clearly and makes sure you feel confident behind the wheel. Her teaching style is friendly but firm.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Chandra Prakash",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Lakshmi ma'am is a very non-commercial person with a golden heart. She teaches in minimum sessions and excellent skills pretty fast, I referred a lot of people and they all got their license within a short time, even my daughter who I thought would take longer.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Rajesh Kannan",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "She is absolutely professional, patient and ensures to fine tune your areas of weaknesses. I have been lucky to have her as my instructor from lucky driving school and thankful to her for transforming me into a confident driver on the road.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Komal Majethiya",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Lakshmi is very polite, and helpful. She always encouraged me a lot and helped me gain the confidence about driving. The best thing about her is that she works around your schedule. Highly recommend her.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Aishwarya Murthy",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Love everything! She is so calm and patient in teaching and very detail oriented. Plus, if you are looking for a girl's girl instructor, here she is. I passed my DL test once for all with her being my actual proper instructor needed for the Alberta roads! And very affordable too!",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Promise",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Lakshmi is an amazing teacher. She taught me everything I needed to pass my driving exam in one try. Highly recommend!",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Vanessa Destiana",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "When I first started, I didn't have any previous experience and I was really nervous to get behind the wheel. For someone who tends to be really nervous, I am really grateful for Lakshmi for her teaching and patience. She gave me clear and helpful instructions, and I was able to confidently pass my driving test.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Mosline Dembo",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "When I first started, I only knew how to move a car. As long as it was a straight road without turns. But with Lucky driving school I got to know all there is to driving.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Shirisha Koti",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Lakshmi is a fantastic instructor who explains everything clearly and calmly. Always punctual, patient, and supportive, which made learning to drive stress-free. I passed my test successfully thanks to their guidance. I would strongly recommend them to anyone learning to drive.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Pushpa Latha",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "I first signed up with another driving school, but they weren't very professional. A friend recommended this school, and I'm glad they did. Lakshmi explains driving skills in a practical, hands-on way, which made all the difference.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Santhosh Kumar",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "I had driving experience from India but failed my road test earlier due to a very stressful instructor, which caused fear in driving. Then my friend recommended her, and she was amazing — very patient, soft-spoken, and supportive.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Arwa Makati",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "I should say the best driving instructor in Edmonton. I am glad i took my lessons from her. I am a novice driver and had never drove a car before but after taking lessons from her i feel i have been driving since many years. Anyone in Edmonton looking for driving lessons should definitely consider Lucky Driving School.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Sujata Balivada",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Lucky Driving School is truly one of the best driving schools in Edmonton. From the first lesson itself, Instructor Lakshmi showed outstanding professionalism, patience, and teaching skills. She guided my son Sharat through every step with care and expertise.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Sumalatha Ummala",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Lakshmi is my wonderful teacher! She teaches skills in very simple easy to understand ways and gives many helpful tips along the way. She is constructive confident in my driving abilities, thank you lakshmi.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Iryna Kazakova",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "The best driving licensed school in the Edmonton area! Very knowledgeable and kind instructor, great explanation! I had the best experience with Lakshmi, she is sooo helpful! I was absolutely zero in driving, but thanks to her I am great now! Highly recommend her to my friends and relatives!",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Chioma Ezeudenna",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Ms lucky the instructor was very patient with me, such a great teacher. Lucky driving school is a school that makes your driving learning period seamless.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Misbah Ahmed",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Lakshmi is the best teacher ever! She's very patient and very clear at giving instructions, and knows exactly when you're ready to take your test. 100% recommend!",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Shobha P",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Lakshmi Prasanna is a perfect choice if you are feeling anxious about getting behind the wheel. She never raised her voice and always focused on building my confidence before moving to busier roads.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Melody Lovlin",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Lakshmi Alluri was the best driving instructor I could have asked for! I had barely driven before my lessons and was quite nervous to learn as an adult/felt very behind, but she was always calm, communicative and helpful. I ended up getting my license on the first try!",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Bhavani Kancharla",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Lakshmi garu is a very skilled and professional instructor. Her clear guidance made me feel confident and at ease while learning to drive, leading to a successful driving test result. Highly recommend her.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Daniel Daudu",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Had a great training experience working with Lucky. She is clear in her communication, knowledgeable and experienced. She is also helpful and gives very useful tips for practical driving that are well grounded in safety rules. Will 100% recommend her to anyone looking prepare for their Class 5!",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Moduga Kishore",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Thank you so much for guiding my son and giving confidence to attend exam earlier than he thought. You are really a trustworthy driving school providing excellent service and customer satisfaction, great job. Thank you again.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Aashna Kapoor",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Lakshmi aunty is an amazing driving instructor. She made me feel very comfortable with driving, even though I had never driven a car before. I recommend everyone to learn to drive with her.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Weldeab Samuel",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "Great Instructor! My instructor was patient, clear, and very supportive. She helped me feel confident and prepared, and I highly recommend her to anyone looking for a supportive instructor.",
    status: "approved",
    isGoogleReview: true,
  },
  {
    name: "Jes Mindi",
    email: "google-review@luckydrivingschool.net",
    rating: 5,
    comment: "I can confidently say that Lakshmi Alluri is the best instructor you could ask for. She's with you every step of the way, ensuring you understand everything and feel ready. Her guidance made all the difference—I passed on my first try!",
    status: "approved",
    isGoogleReview: true,
  },
]
